### ISSUE TITLE
精读趣谈网络协议

### ISSUE THREAD

**Issue by FrankKai** [FrankKai/FrankKai.github.io#93]
在极客时间上订阅了刘超老师的《趣谈网络协议》专栏，在这个issue中，我将按照专栏文章章节，摘取自己认为比较重要的网络协议知识点，并且写一些自己的看法。

**Comment by FrankKai** [comment]
第1讲：为什么要学习网络协议？
#### 语言也是一种协议
只有通过这种协议，计算机才知道我们想让它做什么。
#### 计算机语言协议三要素
- 语法
- 语义
- 顺序
#### 网络协议的意义
只有通过网络协议，才能使一大片机器互相协作、共同完成一件事。
####  网关和MAC地址的作用？
网关是一个路由器，通过路由表，知道到某个IP怎么走。
通过网卡的MAC地址，可以唯一定位目标服务器，也可以唯一定位客户端电脑。
#### 目标服务器被找到后做什么操作？
目标服务器发现 MAC 地址对上了，取下 MAC 头来，发送给操作系统的网络层。发现 IP 也对上了，就取下 IP 头。IP 头里会写上一层封装的是 TCP 协议，然后将其交给传输层，即TCP层。
![image](https://user-images.githubusercontent.com/19262750/44890789-970a9280-ad0e-11e8-807d-60cb18df0c4d.png)
#### 大佬们经常说的ACK是什么？
**在TCP层里，对于收到的每个包，都会有一个回复的包说明收到了。这个回复的包绝非这次下单请求的结果，例如购物是否成功，扣了多少钱等，而仅仅是 TCP 层的一个说明，即收到之后的回复。当然这个回复，会沿着刚才来的方向走回去，报个平安。
如果过一段时间还是没到，发送端的 TCP 层会重新发送这个包，还是上面的过程，直到有一天收到平安到达的回复。
这个重试绝非你的浏览器重新将下单这个动作重新请求一次。对于浏览器来讲，就发送了一次下单请求，TCP 层不断自己闷头重试。除非 TCP 这一层出了问题，例如连接断了，才轮到浏览器的应用层重新发送下单请求。**
![image](https://user-images.githubusercontent.com/19262750/44891750-9de7d400-ad13-11e8-8a8a-41ca5eb52ea6.png)
#### Tomcat与协议之间的关系
##### 什么时候Tomcat与协议间建立联系
网络包到达TCP层之后，TCP头中有目标端口号，通过这个端口号，可以找到电商网站监听此端口号的进程，而这个监听者，就可能是Tomcat
##### Tomcat 的职责-HTTP请求统筹处理者
- 告诉订单进程，登记商品，买多少
- 告诉库存进程，库存减少多少
- 告诉支付进程，应该付多少钱
##### Tomcat如何告诉相关进程
- RPC调用，也就是远程过程调用
- RPC调用时告诉相关进程时，不需要关心**网络互连（涉及RPC协议）**问题，会有RPC框架统一处理
- RPC框架很多种，放HTTP报文，放TCP报文等等
####

**Comment by FrankKai** [comment]
### 第2讲：网络分层的真实含义是什么？
**二层设备、三层设备、四层LB和七层LB中层**
#### 不恰当的网络分层比喻
为什么网络要分层呀？因为不同的层次之间有不同的沟通方式，这个叫作协议。例如，一家公司也是分“层次”的，分总经理、经理、组长、员工。总经理之间有他们的沟通方式，经理和经理之间也有沟通方式，同理组长和员工。

#### 几个协议之间的联系的问题
- 经理与经理间握手时，员工在做什么？对应TCP建立连接的三次握手协议，TCP在进行3次握手的时候，IP层与MAC层对应有什么操作？
- 原始地址 A 到目标地址 D，中间经过两个中转站 A->B->C->D，A知道自己的下一个中转站是B，那A发出来的包，应该把B的IP地址放在哪里？
- 二层设备处理的通常是 MAC 层的东西。二层设备处理的包里，有没有 HTTP 层的内容呢？

#### 一个综合的网络协议的问题
- 从我们的电脑，通过SSH登录到公有云主机里面，都需要经历哪些过程？
- 打开一个电商网站，需要经历哪些过程？

**Comment by FrankKai** [comment]
### 第3讲| ifconfig:最熟悉又陌生的命令行
#### 与ifconfig相同的在linux系统上查看ip地址的命令是什么？
ip addr

**Comment by FrankKai** [comment]
### 第4讲 | DHCP与PXE: IP是怎么来的，又是怎么没的？
#### 如何配置IP地址？
**使用net-tools: **
```
$ sudo ifconfig eth1 10.0.0.1/24
$ sudo ifconfig eh1 up
```
**使用iproute2: **
```
$ sudo ip addr add 10.0.0.1/24 dev eth1
$ sudo ip link set up eth1
```
配置错了会有什么影响？发布出去包。

**Comment by FrankKai** [comment]
### 第5讲 | 从物理层到MAC层：如何在宿舍里自己组网玩联机游戏？
#### 2台机器在物理层组一个LAN（局域网）即可，有3台机器的时候，该怎么组网呢？
- 这个包时发给谁的？应该谁接收？
- 大家都在发，会不会产生混乱？有没有谁先发、谁后发的规则？
- 发送时出现了错误，怎么办？

这些问题都是二层，即数据链路层，MAC（Medium Access Control，媒体访问控制）层解决的问题。

#### MAC层控制的是什么？
控制谁先发，谁后发的问题，防止发生混乱。专业名称叫多路访问。

#### 多路访问的几种实现方式
- **信道划分** 多个车道，每个车一个车道。
- **轮流协议** 单双号限行，今天单号，明天双号。
- **随机接入协议** 先出门，堵了就回去，错过高峰出门。以太网就是这种方式

**Comment by FrankKai** [comment]
### 第6讲 | 交换机与VLAN：办公室太复杂，我要回学校

#### 拓扑结构是怎么形成的？
一般来说，公司里会有很多机器，每台机器对应一个网口，少则几十台，多则几百台，上千上万台，此时一个交换机就不够用了，需要多台交换机，交换机之间连接起来，就形成了一个复杂的**拓扑结构**。

**Comment by FrankKai** [comment]
### 第7讲 | ICMP 与ping：投石问路的侦察兵
- 网络不通第一反应是ping，那么ping是如何工作的？

#### 网络不通第一反应是ping，那么ping是如何工作的？
ping是通过ICMP协议工作的。ICMP全称为Internet Control Message Protocol，互联网控制信息协议。

**Comment by FrankKai** [comment]
### 第8讲 | 世界那么大，我想出网关：欧洲十国游与玄奘西行
- 你知道MAC头和IP头的细节吗？
![image](https://user-images.githubusercontent.com/19262750/47908390-1449b380-dec8-11e8-90fa-444238b42bf4.png)

Gateway知识点
- 若两台机器不在同一网段，那么就需要默认网关，Gateway。
- Gateway的地址总是和源ip地址在一个网段的，例如源ip为192.168.1.144，那么Gateway的地址要么是192.168.1.1，要么是192.168.1.2。此时网段为192.168.1.0/24。

**Comment by FrankKai** [comment]
### 第9讲 | 路由协议：西出网关无故人，敢问路在何方
#### 通过目的IP地址配置路由
- 目的网络：包想去哪儿？
- 出口设备：包从哪个口出去？
- 下一跳网关：下一个路由器的地址。

`ip route add 10.176.48.0/20 via 10.173.32.1 dev eth0`
就说明要去 10.176.48.0/20 这个目标网络，要从 eth0 端口出去，经过 10.173.32.1。

#### 配置策略路由
除IP地址外，根据入口设备、TOS等选择路由表。

```
ip rule add from 192.168.1.0/24 table 10 
ip rule add from 192.168.2.0/24 table 20
```
从 192.168.1.10/24 这个网段来的，使用 table 10 中的路由表，而从 192.168.2.0/24 网段来的，使用 table20 的路由表。

还可以按走多路由：
```
ip route add default scope global nexthop via 100.100.100.1 weight 1 nexthop via 200.200.200.1 weight 2
```
下一跳可以是两个地方，100.100.100.1和200.200.200.1，权重分别是1和2.

房东太良心，拉了两个运营商的宽带，因此家里的路由器也换成了可以接2个外网的路由器，一个网速快，一个网速慢。（租房的小伙伴们，如果房东再跟你说家里网速慢没法解决，你可以用处这一招，电信，移动，联通统统接进来。当然，最好是自己买房。）
![image](https://user-images.githubusercontent.com/19262750/48190641-376bdb80-e37e-11e8-91fb-4d3ba7e3c32a.png)
```
$ ip route list table main 
60.190.27.189/30 dev eth3  proto kernel  scope link  src 60.190.27.190
183.134.188.1 dev eth2  proto kernel  scope link  src 183.134.189.34
192.168.1.0/24 dev eth1  proto kernel  scope link  src 192.168.1.1
127.0.0.0/8 dev lo  scope link
default via 183.134.188.1 dev eth2
```

路由器规则：
- 如果去运营商二，就走 eth3；
- 如果去运营商一呢，就走 eth2；
- 如果访问内网，就走 eth1；
- 如果所有的规则都匹配不上，默认走运营商一，也即走快的网络。

若有用户仅仅上个网页，网费便宜一点，怎么办？
1.添加新路由表
```
# echo 200 chao >> /etc/iproute2/rt_tables
```
2.添加规则，让新来的路由表都走新路由表
```
# ip rule add from 192.168.1.101 table chao
# ip rule ls
0:    from all lookup local 
32765:    from 10.0.0.10 lookup chao
32766:    from all lookup main 
32767:    from all lookup default
```
3.默认路由走慢的
```
# ip route add default via 60.190.27.189 dev eth3 table chao
# ip route flush cache
```

**Comment by wolfking0815** [comment]
能分享下pdf文档么？ 我在英国 国内的网站下载动不动就要金币之类的 感觉不靠谱。。。

**Comment by tglxm** [comment]
老师的GitHub是哪个呀？他说写了一个实验教程放到GitHub上，但是我没找到
